---
name: Docker Workflow
on:
  push:
    branches: [main]
    tags: ["v*.*.*"]
  pull_request:
    branches: [main]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: staticrocket/ti-debian
  PUSHING: >-
    ${{ github.event_name != 'pull_request' && github.ref_type == 'tag' }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        include:
          - image-tag: "bookworm-slim"
          - image-tag: "stable-slim"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: 'arm64'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true

      - name: Log into registry ${{ env.REGISTRY }}
        if: ${{ env.PUSHING }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Expose GitHub Runtime
        uses: crazy-max/ghaction-github-runtime@v3

      - name: Build Docker image
        run: make
        env:
          IMAGE_NAME: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          IMAGE_TAG: ${{ matrix.image-tag }}
          BUILD_ARGS: >-
            --cache-to type=gha,scope=${{ matrix.image-tag }}
            --cache-from type=gha,scope=${{ matrix.image-tag }}

      - name: Upload Docker image
        if: ${{ env.PUSHING }}
        run: |
          docker tag $REPOSITORY:$SRC $REPOSITORY:$DST
          docker push -a $REPOSITORY
        env:
          SRC: ${{ matrix.image-tag }}
          DST: ${{ matrix.image-tag }}-${{ github.ref_name }}
          REPOSITORY: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
